on: [workflow_dispatch]

name: Render ICU Status Report

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.0'

      - name: Install packages
        run: |
          install.packages("rmarkdown")
          install.packages("tidyverse")
          install.packages("knitr")
          install.packages("kableExtra")
          install.packages("ggplot2")

      - name: Render report
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: gfm
          path: "ICU status report.qmd"

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
